export const PURCHASE_SUCCESS = "PURCHASE_SUCCESS";
export const PURCHASE_FAILURE = "PURCHASE_FAILURE";
export const PURCHASE_LOADING = "PURCHASE_LOADING";
export const SET_ORDERS = "SET_ORDERS";
export const ORDERS_LOADING = "ORDERS_LOADING";
